# SPDX-FileCopyrightText: 2019-2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

ARG BASE_IMAGE=ubuntu:20.04
FROM "$BASE_IMAGE" as supereight-ci

# Install the required packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
	&& apt-get -y install \
		build-essential \
		git \
		cmake \
		libeigen3-dev \
		libopencv-dev \
		liboctomap-dev \
		openssh-client \
	&& rm -rf /var/lib/apt/lists/*

# Set the directory the shell is in after starting the container
WORKDIR /usr/local/src/

